name: Terraform code removal

on:
  push:
    branches:
      - main
    paths:
      - "Terraform-Deployment/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: technova-codedeploy-bucket
  CODEDEPLOY_APP: technova-codedeploy
  CODEDEPLOY_GROUP: techonva-deploy-group 

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Initialize
        working-directory: ./Terraform-Deployment
        run: terraform init

      - name: Terraform Code Validation
        working-directory: ./Terraform-Deployment
        run: terraform validate

      - name: Terraform Plan Status
        working-directory: ./Terraform-Deployment
        run: terraform plan

      - name: Apply Terraform Changes
        working-directory: ./Terraform-Deployment
        run: terraform destroy -auto-approve
