name:  CI/CD Pipeline TechNova-Application

on:
  push:
    branches:
      - main
    paths:
      - "technova-node-app/**"


env:
  IMAGE_NAME: booraraman/technova-app
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build-and-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./technova-node-app
        run: |
          npm install
          npm install -g nodemon express mongoose

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} ./technova-node-app
          echo "Built Docker image: $IMAGE_NAME:${{ env.IMAGE_TAG }}"

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
          echo "Pushed Docker image: $IMAGE_NAME:${{ env.IMAGE_TAG }}"
