name: Strapi CI/CD Pipeline For ECS Task Updation File

on:
  push:
    paths:

"strapi-app-latest/**"

env:
  IMAGE_NAME: booraraman/strapi-app
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build-and-push:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:

name: Checkout Code
      uses: actions/checkout@v4


name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22


name: Install Dependencies
      working-directory: ./strapi-app-latest
      run: npm install


name: Run Syntax Check
      working-directory: ./strapi-app-latest
      run: |
        echo "Syntax check passed (Add lint/test if needed)"# npm run lint or npm run test


name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} ./strapi-app-latest
        echo "Built Docker image: $IMAGE_NAME:${{ env.IMAGE_TAG }}"


name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
        echo "Pushed Docker image: $IMAGE_NAME:${{ env.IMAGE_TAG }}"


name: Save Image Tag and Repo as Artifacts
      run: |
        echo "${{ env.IMAGE_TAG }}" > image-tag.txt
        echo "${{ env.IMAGE_NAME }}" > image-repo.txt
